"""weather_add_cartesian

Revision ID: 12886d7c997b
Revises: 575d5ba82cab
Create Date: 2023-02-12 00:17:37.777717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12886d7c997b'
down_revision = '575d5ba82cab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecast', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('weather_forecast', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecast', 'longitude')
    op.drop_column('weather_forecast', 'latitude')
    # ### end Alembic commands ###
