"""update_foreignkeys

Revision ID: 2c98c8dfb550
Revises: 96150e475df8
Create Date: 2023-03-07 17:10:47.139180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "2c98c8dfb550"
down_revision = "96150e475df8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
