"""blockers

Revision ID: 2d689e432f89
Revises: d10beb6524cf
Create Date: 2023-02-13 18:32:43.684399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d689e432f89'
down_revision = 'd10beb6524cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['tasks_action.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['tasks_action.id'], ),
    sa.PrimaryKeyConstraint('id', 'blocker_id', 'blocked_id')
    )
    op.create_index(op.f('ix_tasks_block_id'), 'tasks_block', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_block_id'), table_name='tasks_block')
    op.drop_table('tasks_block')
    # ### end Alembic commands ###
