"""nullable fields

Revision ID: 39903670ca55
Revises: 67e93014d224
Create Date: 2023-02-26 21:09:10.346040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39903670ca55"
down_revision = "67e93014d224"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weather_alert", "onset", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "weather_alert", "ends", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "weather_alert", "headline", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("weather_alert", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_alert",
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "weather_alert", "headline", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "weather_alert", "ends", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "weather_alert", "onset", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
