"""sensors

Revision ID: 49b2ea32058b
Revises: 2c98c8dfb550
Create Date: 2023-03-08 19:41:28.150596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "49b2ea32058b"
down_revision = "2c98c8dfb550"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_sensor",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("model", sa.Integer(), nullable=False),
        sa.Column("measurement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_sensor_sensor_uuid"), "sensor_sensor", ["uuid"], unique=False
    )
    op.create_table(
        "garden_sensorlinktable",
        sa.Column("sensor_sensor_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("garden_bed_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_bed_uuid"],
            ["garden_bed.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_sensor_uuid"],
            ["sensor_sensor.uuid"],
        ),
        sa.PrimaryKeyConstraint("sensor_sensor_uuid", "garden_bed_uuid"),
    )
    op.drop_column("pantry_consumed", "unit")
    op.add_column("pantry_stocked", sa.Column("amount", sa.Float(), nullable=False))
    op.drop_column("pantry_stocked", "count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pantry_stocked",
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("pantry_stocked", "amount")
    op.add_column(
        "pantry_consumed",
        sa.Column("unit", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("garden_sensorlinktable")
    op.drop_index(op.f("ix_sensor_sensor_uuid"), table_name="sensor_sensor")
    op.drop_table("sensor_sensor")
    # ### end Alembic commands ###
