"""weather_forecast

Revision ID: 575d5ba82cab
Revises: da0a3a3cdbab
Create Date: 2023-02-12 00:16:31.602507

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '575d5ba82cab'
down_revision = 'da0a3a3cdbab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_daytime', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('temperature_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probability_of_precipitation', sa.Float(), nullable=True),
    sa.Column('dewpoint', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('windspeed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wind_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_forecast', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detailed_forecast', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
