"""remove_sensor-state

Revision ID: 6684d5ef7f11
Revises: b6a99f1a9c35
Create Date: 2023-02-08 22:49:23.937698

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "6684d5ef7f11"
down_revision = "b6a99f1a9c35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "garden_plant", "raisedbed_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "sensors_sensor", sa.Column("coords_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "sensors_sensor_coords_fkey", "sensors_sensor", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "sensors_sensor", "location_gpscoords", ["coords_id"], ["id"]
    )
    op.drop_column("sensors_sensor", "state")
    op.drop_column("sensors_sensor", "coords")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensors_sensor",
        sa.Column("coords", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "sensors_sensor",
        sa.Column("state", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "sensors_sensor", type_="foreignkey")
    op.create_foreign_key(
        "sensors_sensor_coords_fkey",
        "sensors_sensor",
        "location_gpscoords",
        ["coords"],
        ["id"],
    )
    op.drop_column("sensors_sensor", "coords_id")
    op.alter_column(
        "garden_plant", "raisedbed_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
