"""update column names

Revision ID: 67e93014d224
Revises: 9895c87ade74
Create Date: 2023-02-26 19:43:09.520423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "67e93014d224"
down_revision = "9895c87ade74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_alert",
        sa.Column("message_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "weather_alert",
        sa.Column("sender_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("weather_alert", "senderName")
    op.drop_column("weather_alert", "messageType")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_alert",
        sa.Column("messageType", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "weather_alert",
        sa.Column("senderName", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("weather_alert", "sender_name")
    op.drop_column("weather_alert", "message_type")
    # ### end Alembic commands ###
