"""container type

Revision ID: 7d9d9f3c4b1f
Revises: f0b4afadf04e
Create Date: 2023-03-10 19:38:18.543547

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "7d9d9f3c4b1f"
down_revision = "f0b4afadf04e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pantry_container",
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pantry_container", "type")
    # ### end Alembic commands ###
