"""index_item-type

Revision ID: 7e58458313a1
Revises: 1913b1bf9b7e
Create Date: 2023-02-08 23:05:39.328141

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "7e58458313a1"
down_revision = "1913b1bf9b7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_inventory_item_type"), "inventory_item", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_item_type"), table_name="inventory_item")
    # ### end Alembic commands ###
