"""add raisedbed size

Revision ID: 80f9da743065
Revises: d4085fdfb759
Create Date: 2023-02-21 10:42:45.620190

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "80f9da743065"
down_revision = "d4085fdfb759"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("garden_raisedbed", sa.Column("width", sa.Float(), nullable=False))
    op.add_column("garden_raisedbed", sa.Column("length", sa.Float(), nullable=False))
    op.add_column("garden_raisedbed", sa.Column("height", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("garden_raisedbed", "height")
    op.drop_column("garden_raisedbed", "length")
    op.drop_column("garden_raisedbed", "width")
    # ### end Alembic commands ###
