"""make nullable

Revision ID: 9895c87ade74
Revises: f7e8ac34191d
Create Date: 2023-02-26 19:42:33.398200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "9895c87ade74"
down_revision = "f7e8ac34191d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weather_alert", "instruction", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weather_alert", "instruction", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
