"""blocker_update

Revision ID: 991c7434f4d3
Revises: 9f68852b2b02
Create Date: 2023-02-13 23:37:53.428007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '991c7434f4d3'
down_revision = '9f68852b2b02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['tasks_action.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['tasks_action.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.drop_index('ix_tasks_block_id', table_name='tasks_block')
    op.drop_table('tasks_block')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_block',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('blocker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['tasks_action.id'], name='tasks_block_blocked_id_fkey'),
    sa.ForeignKeyConstraint(['blocker_id'], ['tasks_action.id'], name='tasks_block_blocker_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'blocker_id', 'blocked_id', name='tasks_block_pkey')
    )
    op.create_index('ix_tasks_block_id', 'tasks_block', ['id'], unique=False)
    op.drop_table('block')
    # ### end Alembic commands ###
