"""update data

Revision ID: 9c2612456fdc
Revises: b221de6ba85b
Create Date: 2023-03-03 19:27:15.969286

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9c2612456fdc"
down_revision = "b221de6ba85b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garden_growthscheduledata",
        sa.Column("inventory_item_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("germinate", sa.Interval(), nullable=False),
        sa.Column("plant", sa.Interval(), nullable=False),
        sa.Column("harvest", sa.Interval(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_growthscheduledata_uuid"),
        "garden_growthscheduledata",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "garden_wateringscheduledata",
        sa.Column("inventory_item_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("gallons", sa.Float(), nullable=False),
        sa.Column("period", sa.Interval(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_wateringscheduledata_uuid"),
        "garden_wateringscheduledata",
        ["uuid"],
        unique=False,
    )
    op.drop_index("ix_garden_scheduledata_uuid", table_name="garden_scheduledata")
    op.drop_table("garden_scheduledata")
    op.alter_column(
        "garden_raisedbed",
        "garden_irrigationgrid_uuid",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "garden_raisedbed",
        "garden_irrigationgrid_uuid",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    op.create_table(
        "garden_scheduledata",
        sa.Column(
            "inventory_item_uuid",
            postgresql.UUID(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("uuid", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "germinated", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "planted", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "harvested", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
            name="garden_scheduledata_inventory_item_uuid_fkey",
        ),
        sa.PrimaryKeyConstraint("uuid", name="garden_scheduledata_pkey"),
    )
    op.create_index(
        "ix_garden_scheduledata_uuid", "garden_scheduledata", ["uuid"], unique=False
    )
    op.drop_index(
        op.f("ix_garden_wateringscheduledata_uuid"),
        table_name="garden_wateringscheduledata",
    )
    op.drop_table("garden_wateringscheduledata")
    op.drop_index(
        op.f("ix_garden_growthscheduledata_uuid"),
        table_name="garden_growthscheduledata",
    )
    op.drop_table("garden_growthscheduledata")
    # ### end Alembic commands ###
