"""block_relationship

Revision ID: 9f68852b2b02
Revises: 2d689e432f89
Create Date: 2023-02-13 23:14:20.282468

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f68852b2b02'
down_revision = '2d689e432f89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
