"""create

Revision ID: b221de6ba85b
Revises: 
Create Date: 2023-03-01 20:53:37.471651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "b221de6ba85b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garden_irrigationhose",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("emitters_per_foot", sa.Float(), nullable=False),
        sa.Column("gallons_per_hour", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("type", "emitters_per_foot", "gallons_per_hour"),
    )
    op.create_index(
        op.f("ix_garden_irrigationhose_uuid"),
        "garden_irrigationhose",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "inventory_item",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_inventory_item_type"), "inventory_item", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_item_uuid"), "inventory_item", ["uuid"], unique=False
    )
    op.create_table(
        "location_gpscoords",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("latitude", "longitude", "elevation"),
    )
    op.create_index(
        op.f("ix_location_gpscoords_uuid"), "location_gpscoords", ["uuid"], unique=False
    )
    op.create_table(
        "pantry_container",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("units", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_pantry_container_uuid"), "pantry_container", ["uuid"], unique=False
    )
    op.create_table(
        "garden_irrigationgrid",
        sa.Column(
            "garden_irrigationhose_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("length", sa.Float(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_irrigationhose_uuid"],
            ["garden_irrigationhose.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_irrigationgrid_uuid"),
        "garden_irrigationgrid",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "garden_scheduledata",
        sa.Column("inventory_item_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("germinated", sa.Interval(), nullable=False),
        sa.Column("planted", sa.Interval(), nullable=False),
        sa.Column("harvested", sa.Interval(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_scheduledata_uuid"),
        "garden_scheduledata",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "pantry_stockedgood",
        sa.Column("inventory_item_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "pantry_container_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("packed", sa.DateTime(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["pantry_container_uuid"],
            ["pantry_container.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_pantry_stockedgood_uuid"), "pantry_stockedgood", ["uuid"], unique=False
    )
    op.create_table(
        "weather_alert",
        sa.Column(
            "location_gpscoords_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("noaa_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent", sa.DateTime(), nullable=False),
        sa.Column("effective", sa.DateTime(), nullable=False),
        sa.Column("onset", sa.DateTime(), nullable=True),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("ends", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("urgency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("headline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_gpscoords_uuid"],
            ["location_gpscoords.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("noaa_id"),
    )
    op.create_index(
        op.f("ix_weather_alert_uuid"), "weather_alert", ["uuid"], unique=False
    )
    op.create_table(
        "garden_raisedbed",
        sa.Column(
            "location_gpscoords_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "garden_irrigationgrid_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=True
        ),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("length", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_irrigationgrid_uuid"],
            ["garden_irrigationgrid.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["location_gpscoords_uuid"],
            ["location_gpscoords.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_raisedbed_uuid"), "garden_raisedbed", ["uuid"], unique=False
    )
    op.create_table(
        "pantry_consumed",
        sa.Column(
            "pantry_stockedgood_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pantry_stockedgood_uuid"],
            ["pantry_stockedgood.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_pantry_consumed_uuid"), "pantry_consumed", ["uuid"], unique=False
    )
    op.create_table(
        "garden_crop",
        sa.Column("inventory_item_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "garden_raisedbed_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_raisedbed_uuid"],
            ["garden_raisedbed.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_uuid"],
            ["inventory_item.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_garden_crop_uuid"), "garden_crop", ["uuid"], unique=False)
    op.create_table(
        "garden_action",
        sa.Column("garden_crop_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_crop_uuid"],
            ["garden_crop.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_garden_action_uuid"), "garden_action", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_garden_action_uuid"), table_name="garden_action")
    op.drop_table("garden_action")
    op.drop_index(op.f("ix_garden_crop_uuid"), table_name="garden_crop")
    op.drop_table("garden_crop")
    op.drop_index(op.f("ix_pantry_consumed_uuid"), table_name="pantry_consumed")
    op.drop_table("pantry_consumed")
    op.drop_index(op.f("ix_garden_raisedbed_uuid"), table_name="garden_raisedbed")
    op.drop_table("garden_raisedbed")
    op.drop_index(op.f("ix_weather_alert_uuid"), table_name="weather_alert")
    op.drop_table("weather_alert")
    op.drop_index(op.f("ix_pantry_stockedgood_uuid"), table_name="pantry_stockedgood")
    op.drop_table("pantry_stockedgood")
    op.drop_index(op.f("ix_garden_scheduledata_uuid"), table_name="garden_scheduledata")
    op.drop_table("garden_scheduledata")
    op.drop_index(
        op.f("ix_garden_irrigationgrid_uuid"), table_name="garden_irrigationgrid"
    )
    op.drop_table("garden_irrigationgrid")
    op.drop_index(op.f("ix_pantry_container_uuid"), table_name="pantry_container")
    op.drop_table("pantry_container")
    op.drop_index(op.f("ix_location_gpscoords_uuid"), table_name="location_gpscoords")
    op.drop_table("location_gpscoords")
    op.drop_index(op.f("ix_inventory_item_uuid"), table_name="inventory_item")
    op.drop_index(op.f("ix_inventory_item_type"), table_name="inventory_item")
    op.drop_table("inventory_item")
    op.drop_index(
        op.f("ix_garden_irrigationhose_uuid"), table_name="garden_irrigationhose"
    )
    op.drop_table("garden_irrigationhose")
    # ### end Alembic commands ###
