"""fix amount

Revision ID: df03c217d7d6
Revises: 7d9d9f3c4b1f
Create Date: 2023-03-10 19:46:51.391170

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "df03c217d7d6"
down_revision = "7d9d9f3c4b1f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
