"""update weather contraints

Revision ID: f7e8ac34191d
Revises: 7b6e4ed35942
Create Date: 2023-02-26 19:41:55.107605

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f7e8ac34191d"
down_revision = "7b6e4ed35942"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "weather_alert", ["noaa_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weather_alert", type_="unique")
    # ### end Alembic commands ###
